### ISSUE TITLE
Support loading API schema by version tag

### ISSUE THREAD

**Issue by lorddaedra** [getlago/lago-openapi#16]
### Problem

- Currently we can load `latest` (note here: it's bad DevOps practice to use `latest` tags in production) version of OpenAPI schema (from main branch): `https://raw.githubusercontent.com/getlago/lago-openapi/main/swagger.yaml`,
- Also we can load `v0.22.1-beta` version `https://github.com/getlago/lago-openapi/blob/v0.22.1-beta/swagger.yaml`. 

For client development (I mean auto generated Pydantic models for Python client) it should be possible to load API schema by version. This should be automatic process (without delays and human errors).

### Solution

After merging something to `main` branch:

- Read `info.version` from `swagger.yaml` using https://github.com/marketplace/actions/read-yaml
- Create new (if not exist) or move current (?) tag to latest commit using https://github.com/marketplace/actions/create-update-tag (with `force_push_tag: true`?)

P.S. I suggest also to support 2 latest schema version in all clients (may be you should add support policy document to docs). So your customers can update client (which uses Python Lago client) then server (Lago API) in two separate steps (it may be hard to deploy Lago API and main app with Lago client together in the same deploy operation). So do not make breaking changes in closest releases.

**Comment by jdenquin** [comment]
we have to create a tag each time we release a new lago version, it's not automated right now but will be very soon!
