### ISSUE TITLE
[BUG]: Unnecessary allOf generates unnecessary class

### ISSUE THREAD

**Issue by algra4** [getlago/lago-openapi#300]
**Describe the bug**
Sometimes, the allOf keyword is used in the wrong case if we follow the [spec](https://swagger.io/docs/specification/v3_0/data-models/oneof-anyof-allof-not/#allof).

This intensive use produces empty classes in java (I don't know for other language).
Fo example, for the `CustomerObjectExtended` object, the attribut `country` is a class named `CustomerObjectAllOfCountry` but it's empty instead of `Country` enum

**To Reproduce**
Example:
In [AddOnBaseInput](https://github.com/getlago/lago-openapi/blob/d6250657dd4392babb83096829493babd45872d8/src/schemas/AddOnBaseInput.yaml#L20) schema an `allOf` is defined for `amount_currency` attribut but it's not required. 

**Expected behavior**
Using allOf only when it's necessary.

**Screenshots**
N/A

**Support**
N/A

**Additional context**
N/A

**Comment by algra4** [comment]
It's fixed on this PR: #299

**Comment by vincent-pochet** [comment]
Closing it as https://github.com/getlago/lago-openapi/pull/299 has been merged
