### ISSUE TITLE
Rename `swagger.yaml` to `openapi.yaml`

### ISSUE THREAD

**Issue by lorddaedra** [getlago/lago-openapi#31]
Rename `swagger.yaml` file to `openapi.yaml` because of "swagger" means version 2.0 or lesser

Proof:
https://spec.openapis.org/oas/latest.html#appendix-a-revision-history

**Comment by vincent-pochet** [comment]
Thanks for opening this issue.
It sounds fine to rename this file, but it as some implication on the existing usage of this file.

For example, it will impact the [documentation](https://github.com/getlago/lago-docs/blob/main/docs/guide/99_openapi.md),

**Comment by vincent-pochet** [comment]
Well option 1 sounds fine I guess, we have no need to have it in "real-time" :)
