### ISSUE TITLE
(On Hold) Add `null` type support for properties

### ISSUE THREAD

**Issue by lorddaedra** [getlago/lago-openapi#32]
Currently OpenAPI schema provide support for `required` fields. (it means key must exist)

But what if key exists but value is `null`? We need add `null` type support to mark fields which may return `null` instead of other values.

Docs (as usual) is "source of truth".

Depends on: 
- #28  
(not a dependency really but it will be much simpler to review changes because of '< type >' and 'null' words will be closer to each other)

**Comment by vincent-pochet** [comment]
Closing this issue as it has been fixed with the recent updates of the openAPI file
